name: reportr
version: 1.0.0+1
description: A new Flutter module project.
environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  firebase_auth: ^4.4.0
  image_picker: ^0.8.7+1
  flutter_animate: ^4.1.1+1
  cloud_firestore: ^4.5.0
  uuid: ^3.0.7
  image_picker_android: ^0.8.6+6
  firebase_storage: ^11.1.0
  cached_network_image: ^3.2.3
  path: ^1.8.2
  marker_icon: ^0.7.1
  flex_color_picker: ^3.2.0
  crypt: ^4.2.1
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.10
  get_storage: ^2.1.1
  crop_your_image: ^0.7.2
  file_picker: ^5.2.10
  dio: ^5.1.1
  dynamic_color: ^1.6.3
  extended_text_field: ^12.1.0
  auto_size_text_field: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/
